### ISSUE TITLE
RCSモジュール　GPIO18,19の出力が低い

### ISSUE THREAD

**Issue by KeisukeSuganuma** [wasa-rockoon/WOBC#39]
RCSモジュールの動作確認中に電磁弁のスイッチであるピンの出力電圧が低いことがわかりました。
色々試してみましたが、RP2040の故障ではないかと思っています。
後日学生会館に置いてきた予備基板を用いて再確認を行うつもりですが、その前にこの回路で出力が下がる要因があるかお尋ねしたいです。
ちなみに出力電圧は他のピンであれば3.3V出ており、18,19ピンのみ0.6V程度しか出ません。他のモジュール(Controllerモジュール)で同じプログラムを書き込んだら3.3V出ています。ONOFFは切り替えられるようで、0V⇄0.6Vの切り替えは可能です。

何か心当たりがあれば教えて下さい！
![image](https://github.com/user-attachments/assets/fa7e6d0b-c767-463d-9e38-60936ab39dec)

**Comment by KeisukeSuganuma** [comment]
すみません画像が切れていますがこの下部は3本ともすべてGNDにつながっています

**Comment by fujiy** [comment]
うーん
電磁弁の電源をONしない場合でも同じく0.6Vが出る？

**Comment by KeisukeSuganuma** [comment]
すみません、説明不足でした。
電磁弁が手元にないので今電磁弁はつながっていません。
NMOSのドレインは浮いている状態です。

**Comment by fujiy** [comment]
なるほど
電磁弁は一度も繋いだことない？

**Comment by KeisukeSuganuma** [comment]
今のところ一度もないです。

**Comment by fujiy** [comment]
基板データを見てみたんだけど，valve1とvalve2の途中にGNDのビアが刺さってない？

**Comment by KeisukeSuganuma** [comment]
刺さってます？発注基板はMissionOrderFileなのでそっちの方は大丈夫だと思いますけど...
テスターで導通チェックしてみましたが特につながってはなさそうです。

**Comment by fujiy** [comment]
確かにそっちは大丈夫だな
一応プログラム見せてもらえる？

**Comment by KeisukeSuganuma** [comment]
大した量ではないのでここに直接貼ってしまいますね。
ほんとに簡単なものなんですけど、確認お願いします。

#include <Arduino.h>

void setup() {
  pinMode(18, OUTPUT);
  pinMode(19, OUTPUT);

  digitalWrite(18, HIGH);
  digitalWrite(19, HIGH);
}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(18, HIGH);
  digitalWrite(19, HIGH);
  delay(3000);
  digitalWrite(18, LOW);
  digitalWrite(19, LOW);
  delay(3000);
}

**Comment by fujiy** [comment]
うーんわからないなあ
どこかとショートしてるくらいしか思いつかないな

今回のとは関係ないけど，電磁弁に並行にフリーホイールダイオードを追加しないと逆起電力で回路壊れるかも

**Comment by KeisukeSuganuma** [comment]
なるほど、配線作業のときに繋げます。

ショートですか...見たところ見つからないですねー...もう一個の基板で試してみる他なさそうですね

**Comment by KeisukeSuganuma** [comment]
NMOSの向き間違えでした。
なんとか修正可能です![IMG_20240831_121801.jpg](https://github.com/user-attachments/assets/7ad59f4a-2fab-4f6b-8378-8e72818a79a1)
